from modules.AffectPipeline import AffectPipeline
from rightClickWindow import RightClickWindow


def create_pipeline():
    """
    Creates and returns a configured AffectPipeline
    instance using global PARAMETERS.
    """
    params = RightClickWindow.PARAMETERS

    pipeline = AffectPipeline(
        enable_log_to_console=params.get("enable_log_to_console", True),
        enable_vad_loop=params.get("enable_voiceactivity", False),
        enable_ser_loop=params.get("enable_paralinguistic", False),
        enable_stt_loop=params.get("enable_transcript", False),
        enable_camera_loop=params.get("enable_camera", False),
        enable_print_loop=params.get("enable_print_loop", True),
        enable_send_udp_loop=params.get("enable_udp", False),
        enable_send_kafka_loop=params.get("enable_kafka", False),
        enable_face_er_loop=params.get("enable_facialexpression", False),
        enable_face_mesh_loop=params.get("enable_face_mesh_loop", False),
        enable_pose_loop=params.get("enable_skeleton", False),
        enable_fusion_loop=params.get("enable_fusion", False),
        enable_sentiment_loop=params.get("enable_sentiment", False),
        show_face_mesh=params.get("show_face_mesh", False),
        face_mesh_show_face_edges=params.get("face_mesh_show_face_edges", False),
        face_mesh_show_face_pupils=params.get("face_mesh_show_face_pupils", False),
        face_mesh_show_face_contour=params.get("face_mesh_show_face_contour", False),
        camera_id=params.get("camera_id", 0),
        ser_loop_rate=params.get("SER_LOOP_RATE", 1.0),
        ser_valence_offset=params.get("SER_VALENCE_OFFSET", 0.0),
        ser_arousal_offset=params.get("SER_AROUSAL_OFFSET", 0.0),
        ser_dominance_offset=params.get("SER_DOMINANCE_OFFSET", 0.0),
        stt_loop_rate=params.get("STT_LOOP_RATE", 0.2),
        sentiment_loop_rate=params.get("SENTIMENT_LOOP_RATE", 1.0),
        vad_loop_rate=params.get("VAD_LOOP_RATE", 4.0),
        er_loop_rate=params.get("ER_LOOP_RATE", 2.0),
        pose_loop_rate=params.get("POSE_LOOP_RATE", 4.0),
        fusion_loop_rate=params.get("FUSION_LOOP_RATE", 10.0),
        send_loop_rate=params.get("SEND_LOOP_RATE", 2.0),
        camera_loop_rate=params.get("CAMERA_LOOP_RATE", 4.0),
        logging_loop_rate=params.get("logging_loop_rate", 10.0),
        face_mesh_rate=params.get("FACE_MESH_RATE", 4.0),
        udp_ip=params.get("UDP_IP", "127.0.0.1"),
        udp_port=params.get("UDP_PORT", 5006),
        kafka_ip=params.get("KAFKA_IP", "127.0.0.1"),
        kafka_port=params.get("KAFKA_PORT", 9092),
        kafka_topic_name=params.get("KAFKA_TOPIC", "mithos"),
        sample_rate=params.get("SAMPLE_RATE", 16000),
        vad_threshold=params.get("VAD_THRESHOLD", 0.25),
        face_padding=params.get("FACE_PADDING", 0.2),
        microphone_chunks=params.get("MIC_CHUNKS", 16000),
        microphone_id=params.get("microphone_id", 0),
        stt_window_length=params.get("STT_WINDOW_SIZE", 5.0),
        stt_model_size=params.get("stt_model_size", "base"),
        sentiment_model=params.get("sentiment_model", "multilingual"),
        fusion_use_para_v=params.get("fusion_use_para_v", False),
        fusion_use_para_a=params.get("fusion_use_para_a", False),
        fusion_use_para_d=params.get("fusion_use_para_d", False),
        fusion_use_sentiment_v=params.get("fusion_use_sentiment_v", False),
        fusion_use_face_v=params.get("fusion_use_face_v", False),
        fusion_use_face_a=params.get("fusion_use_face_a", False),
        fusion_use_face_d=params.get("fusion_use_face_d", False),
        fusion_use_pose_d=params.get("fusion_use_pose_d", False),
        fusion_speed=params.get("FUSION_SPEED", 1000),
        fusion_voice_speed=params.get("FUSION_VOICE_SPEED", 5000),
        fusion_voice_valence_weight=params.get("FUSION_VOICE_VALENCE_WEIGHT", 1.0),
        fusion_voice_valence_boost=params.get("FUSION_VOICE_VALENCE_BOOST", 1.0),
        fusion_voice_arousal_weight=params.get("FUSION_VOICE_AROUSAL_WEIGHT", 1.0),
        fusion_voice_arousal_boost=params.get("FUSION_VOICE_AROUSAL_BOOST", 1.0),
        fusion_voice_dominance_weight=params.get("FUSION_VOICE_DOMINANCE_WEIGHT", 1.0),
        fusion_voice_dominance_boost=params.get("FUSION_VOICE_DOMINANCE_BOOST", 1.0),
        fusion_face_speed=params.get("FUSION_FACE_SPEED", 5000),
        fusion_face_valence_weight=params.get("FUSION_FACE_VALENCE_WEIGHT", 1.0),
        fusion_face_valence_boost=params.get("FUSION_FACE_VALENCE_BOOST", 1.25),
        fusion_face_arousal_weight=params.get("FUSION_FACE_AROUSAL_WEIGHT", 0.5),
        fusion_face_arousal_boost=params.get("FUSION_FACE_AROUSAL_BOOST", 1.75),
        fusion_face_dominance_weight=params.get("FUSION_FACE_DOMINANCE_WEIGHT", 1.0),
        fusion_face_dominance_boost=params.get("FUSION_FACE_DOMINANCE_BOOST", 1.25),
        fusion_sentiment_speed=params.get("FUSION_SENTIMENT_SPEED", 5000),
        fusion_sentiment_weight=params.get("FUSION_SENTIMENT_WEIGHT", 1.0),
        fusion_sentiment_boost=params.get("FUSION_SENTIMENT_BOOST", 1.0),
        fusion_pose_speed=params.get("FUSION_POSE_SPEED", 5000),
        fusion_pose_dominance_weight=params.get("FUSION_POSE_DOMINANCE_WEIGHT", 1.0),
        fusion_pose_dominance_boost=params.get("FUSION_POSE_DOMINANCE_BOOST", 1.0)
    )

    return pipeline
